# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Qalq
                                 A QGIS plugin
 automation tool for building unreal engine heightmaps from terrain data
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-29
        copyright            : (C) 2026 by shark_blood_studios
        email                : zacharydubroc@outlook.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load Qalq class from file Qalq.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qalc import Qalc
    return Qalc(iface)
