# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Qalq
                                                                 A QGIS plugin
 automation tool for building unreal engine heightmaps from terrain data
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                                                          -------------------
                begin                : 2026-05-29
                git sha              : $Format:%H$
                copyright            : (C) 2026 by shark_blood_studios
                email                : zacharydubroc@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import json
import urllib.request
import urllib.parse

from qgis.PyQt.QtCore import (
    QLocale,
    QTranslator,
    QCoreApplication,
    QSize,
    QPointF,
    QRectF,
    QObject,
    pyqtSignal,
    QRunnable,
    QThreadPool,
)
from qgis.core import (
    QgsRectangle,
    QgsGeometry,
    Qgis,
    QgsFeature,
    QgsProject,
    QgsRasterLayer,
    QgsSettings,
    QgsMapSettings,
    QgsVectorLayer,
    QgsRasterFileWriter,
    QgsRasterPipe,
    QgsCoordinateTransform,
    QgsCoordinateTransformContext,
    QgsCoordinateReferenceSystem,
    QgsMapRendererParallelJob,
)
from osgeo import gdal
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QMessageBox, QProgressBar
from qgis.PyQt.QtGui import QIcon
from qgis.gui import QgsMapToolEmitPoint, QgsRubberBand
from qgis.PyQt.QtGui import QColor

# Import the code for the dialog
from .qalq_dialog import QalqDialog
import os.path
from urllib.parse import parse_qs, unquote


##selection tool##
# region
class ExtentSet(QgsMapToolEmitPoint):

    def __init__(self, canvas, grid_resolution, iface):
        super().__init__(canvas)
        self.canvas = canvas
        self.size = grid_resolution
        self.isDrawing = True
        self.user_selection = None
        self.rubberBand = QgsRubberBand(canvas, Qgis.GeometryType.Polygon)
        self.rubberBand.setColor(QColor(255, 0, 0, 127))
        self.rubberBand.setWidth(2)
        self.isDrawing = True
        self.iface = iface

    def _updateSquarePreview(self, center):
        half_size = self.size / 2.0
        rect = QgsRectangle(
            center.x() - half_size,
            center.y() - half_size,
            center.x() + half_size,
            center.y() + half_size,
        )
        self.rubberBand.setToGeometry(QgsGeometry.fromRect(rect), None)

    def canvasPressEvent(self, e):
        self.isDrawing = True
        self.currentCenter = self.toMapCoordinates(e.pos())
        self._updateSquarePreview(self.currentCenter)

        center = self.toMapCoordinates(e.pos())
        half_size = self.size / 2.0
        rect = QgsRectangle(
            center.x() - half_size,
            center.y() - half_size,
            center.x() + half_size,
            center.y() + half_size,
        )
        # send execution back to plugin
        self.iface.crop_extent(rect)

    def canvasMoveEvent(self, e):
        if self.isDrawing:
            self.currentCenter = self.toMapCoordinates(e.pos())
            self._updateSquarePreview(self.currentCenter)
        else:
            return

    def canvasReleaseEvent(self, e):
        self.isDrawing = False
        self.canvas.unsetMapTool(self)

    def deactivate(self):
        self.rubberBand.reset()
        super().deactivate()


######
####end selection tool
######
# endregion
##end selection tool##

##osm download##


# region
class QalcSignals(QObject):

    progress = pyqtSignal(int)
    finished = pyqtSignal(str)
    gdal_finished = pyqtSignal(str, float, float, float)
    error = pyqtSignal(str)


class OSMWorker(QRunnable):
    def __init__(self, south, west, north, east, output_directory):
        super().__init__()
        self.signals = QalcSignals()
        self.south = south
        self.west = west
        self.north = north
        self.east = east
        self.output_directory = output_directory

    def run(self):

        self.signals.progress.emit(0)

        bbox = f"{self.south},{self.west},{self.north},{self.east}"
        over_ql = f"""
        [out:xml][timeout:120];
        (
            way["building"]({bbox});
            relation["building"]({bbox});
        );
        (._; >;);
        out body qt;
        """

        endpoints = [
            "https://overpass-api.de/api/interpreter",
            "https://maps.mail.ru/osm/tools/overpass/api/interpreter",
            "https://overpass.private.coffee/api/interpreter"
            ]

        # url = "https://overpass-api.de/api/interpreter"
        output_file = os.path.join(self.output_directory, "aoi_data.osm")
        data = urllib.parse.urlencode({"data": over_ql}).encode("utf-8")
        try:
            for url in endpoints:
                req = urllib.request.Request(
                    url, data=data, headers={"User-Agent": "QGIS-Qalc-Plugin/1.0"}
                )
                with urllib.request.urlopen(req, timeout=130) as response:
                    with open(output_file, "wb") as f:
                        block_size = 1024 * 8
                        while True:
                            buffer = response.read(block_size)
                            if not buffer:
                                break
                            f.write(buffer)
                self.signals.finished.emit(output_file)
                return
        except Exception as e:
            self.signals.error.emit(f"overpass api error: {str(e)}")
# endregion
## end osm download ##

# GDAL worker
class GDALWorker(QRunnable):
    def __init__(
        self, height_input_path, aoi_extent, grid_res, output_dir, albedo_layer
    ):
        super().__init__()
        self.signals = QalcSignals()
        self.height_input_path = height_input_path
        self.aoi_extent = aoi_extent
        self.grid_res = grid_res
        self.output_dir = output_dir
        self.albedo_layer = albedo_layer

    def run(self):
        try:
            self.signals.progress.emit(0)
            proj_win = [
                self.aoi_extent.xMinimum(),
                self.aoi_extent.yMaximum(),
                self.aoi_extent.xMaximum(),
                self.aoi_extent.yMinimum(),
            ]

            cropped_path = f"/vsimem/heightmap_crop.tif"

            translate_opts = gdal.TranslateOptions(
                projWin=proj_win,
                width=self.grid_res,
                height=self.grid_res,
                resampleAlg=gdal.GRIORA_Bilinear,
                creationOptions=["COMPRESS=NONE", "BIGTIFF=IF_NEEDED"],
            )

            ds = gdal.Translate(
                cropped_path, self.height_input_path, options=translate_opts
            )
            if ds is not None:
                ds.FlushCache()

                self.signals.progress.emit(0)
                gtif = gdal.Open(cropped_path)
                elevation_band = gtif.GetRasterBand(1)
                stats = elevation_band.GetStatistics(True, True)
                min_elev = stats[0]
                max_elev = stats[1]
                elev_range = max_elev - min_elev
                gtif = None


            final_path = os.path.join(self.output_dir, "heightmap.png")
            translate_opts = gdal.TranslateOptions(
                format="PNG",
                outputType=gdal.GDT_UInt16,
                scaleParams=[[min_elev, max_elev, 0, 65535]],
            )
            ds = gdal.Translate(final_path, cropped_path, options=translate_opts)
            if ds is not None:
                ds.FlushCache()

            self.signals.gdal_finished.emit(cropped_path, min_elev, max_elev, elev_range)

        except Exception as e:
            QMessageBox.critical(
                self.iface.mainWindow(), "dang", f"height export failed: {str(e)}"
            )


class Qalc:
    # gen from plugin_template
    # region
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
                which provides the hook by which you can manipulate the QGIS
                application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        self.canvas = self.iface.mapCanvas()

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QgsSettings().value("locale/userLocale", QLocale().name())[0:2]
        locale_path = os.path.join(self.plugin_dir, "i18n", "{}.qm".format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&Qalc")

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str

        :returns: Translated version of message.
        :rtype: str
        """
        return QCoreApplication.translate("Qalq", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
                path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
                by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
                be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
                be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
                hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
                mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
                added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)
        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), "icon.png")
        self.add_action(
            icon_path,
            text=self.tr("Qalc"),
            callback=self.run,
            parent=self.iface.mainWindow(),
        )

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr("&Qalc"), action)
            self.iface.removeToolBarIcon(action)

    # endregion
    def run(self):
        """Run method that performs all the real work"""
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = QalqDialog()
            self.dlg.mQgsFileWidget.setStorageMode(self.dlg.mQgsFileWidget.GetDirectory)
            self.dlg.mResolutionComboBox.addItems(["256", "505", "1024"])
            self.dlg.mDPIComboBox.addItems(["150", "300", "600"])
            self.dlg.mResolutionComboBox.setCurrentText("505")
            self.dlg.mDPIComboBox.setCurrentText("300")

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec()
        # See if OK was pressed
        if result:
            # globals set here
            self.height_layer = self.dlg.mMapLayerComboBox.currentLayer()
            self.albedo_layer = self.dlg.mAlbedoLayerComboBox.currentLayer()
            self.cropped_layer = None
            self.selected_directory = self.dlg.mQgsFileWidget.filePath()
            self.grid_resolution = int(self.dlg.mResolutionComboBox.currentText())
            self.DPI = int(self.dlg.mDPIComboBox.currentText())
            self.start()

    def start(self):
        albedo_layer = self.albedo_layer
        height_layer = self.height_layer
        grid_resolution = self.grid_resolution
        selected_directory = self.selected_directory
        height_provider = height_layer.dataProvider().name().lower()
        is_raster = isinstance(height_layer, QgsRasterLayer)
        invalid_providers = {"wms", "wmts", "xyz", "arcgismapserver", "wfs", "wcs"}
        if not height_layer:
            QMessageBox.warning(self.iface.mainWindow(), "dang!", "no layer seleceted!")
            return
        if not selected_directory:
            QMessageBox.warning(
                self.iface.mainWindow(), "dang!", "no output path selected!"
            )
            return
        if height_provider in invalid_providers or not is_raster:
            QMessageBox.warning(
                self.iface.mainWindow(), "dang!", "invalid height layer!"
            )
            return
        try:
            self.tool = ExtentSet(self.canvas, grid_resolution, self)
            self.canvas.setMapTool(self.tool)
        except Exception as e:
            self.iface.messageBar().pushMessage(
                "dang",
                f"an error occurred: {str(e)}",
            )

            ## heightmap ##
    def crop_extent(self, aoi_extent):
        self.aoi_extent = aoi_extent
        height_input_layer = self.height_layer

        height_input_path = (
            height_input_layer.dataProvider().dataSourceUri().split("|")[0]
        )

        w = GDALWorker(
            height_input_path=height_input_path,
            aoi_extent=aoi_extent,
            grid_res=self.grid_resolution,
            output_dir=self.selected_directory,
            albedo_layer=self.albedo_layer,
        )

        self.progress_bar = QProgressBar()
        self.progress_bar.setRange(0, 0)

        w.signals.progress.connect(self.progress_bar.setValue)
        w.signals.gdal_finished.connect(self.on_gdal_success)
        w.signals.error.connect(self.on_gdal_failed)

        msg = self.iface.messageBar().createMessage("Qalc", "exporting images ")
        msg.layout().addWidget(self.progress_bar)
        self.iface.messageBar().pushWidget(msg, Qgis.MessageLevel.Info)

        QThreadPool.globalInstance().start(w)


    def on_gdal_success(self, output_path, min_elev, max_elev, elev_range):
        aoi_extent = self.aoi_extent
        self.iface.messageBar().clearWidgets()
        cropped_layer = QgsRasterLayer(output_path, "heightmap")
        if cropped_layer.isValid():
            QgsProject.instance().addMapLayer(cropped_layer)
            self.cropped_layer = cropped_layer

            z_scale = (elev_range / 512.0) * 100

            self.fetch_osm(self.aoi_extent, self.height_layer.crs())

            self.albedo_export(
                self.aoi_extent,
                self.albedo_layer,
                z_scale,
                min_elev,
                max_elev,
                elev_range,
                self.grid_resolution,
            )


            # self.export_finished(z_scale, min_elev, max_elev, elev_range, self.grid_resolution)

    def on_gdal_failed(self, error_msg):
        self.iface.messageBar().clearWidgets()
        QMessageBox.critical(
            self.iface.mainWindow(), "dang", f"gdal translate failed: {str(error_msg)}"
        )
        ## end heightmap ##
    ## end heightmap ##


    ### overpass start ###
    def fetch_osm(self, aoi_extent, source_crs):

        target_crs = QgsCoordinateReferenceSystem("EPSG:4326")
        transform_context = QgsProject.instance().transformContext()
        transformer = QgsCoordinateTransform(source_crs, target_crs, transform_context)
        wgs_extent = transformer.transformBoundingBox(aoi_extent)

        south = wgs_extent.yMinimum()
        west = wgs_extent.xMinimum()
        north = wgs_extent.yMaximum()
        east = wgs_extent.xMaximum()

        w = OSMWorker(south, west, north, east, self.selected_directory)

        self.progress_bar = QProgressBar()
        self.progress_bar.setRange(0, 0)

        w.signals.progress.connect(self.progress_bar.setValue)
        w.signals.finished.connect(self.on_osm_success)
        w.signals.error.connect(self.on_osm_failed)

        msg = self.iface.messageBar().createMessage("Qalc", "downloading OSM data")
        msg.layout().addWidget(self.progress_bar)
        self.iface.messageBar().pushWidget(msg, Qgis.MessageLevel.Info)

        QThreadPool.globalInstance().start(w)

    def on_osm_success(self, path):
        self.iface.messageBar().clearWidgets()
        self.iface.messageBar().pushMessage(
            "Qalc",
            f"OSM data saved to: {os.path.basename(path)}",
            Qgis.MessageLevel.Success,
            3,
        )

    def on_osm_failed(self, error_msg):
        self.iface.messageBar().clearWidgets()
        QMessageBox.critical(
            self.iface.mainWindow(), "dang", f"OSM download failed: {str(error_msg)}"
        )
    ### overpass end ###

    def albedo_export(
        self,
        aoi_extent,
        albedo_layer,
        z_scale,
        min_elev,
        max_elev,
        elev_range,
        grid_res,
    ):
        # basemap clip -> albedo.png, for texture in ue material
        final_path = os.path.join(
            self.selected_directory, f"{albedo_layer.name()}_albedo.png"
        )
        grid_res = self.grid_resolution
        dpi = self.DPI
        image_location = final_path
        settings = QgsMapSettings()
        settings.setLayers([albedo_layer])
        settings.setBackgroundColor(QColor(255, 255, 255))
        settings.setOutputSize(QSize(grid_res, grid_res))
        settings.setExtent(aoi_extent)
        settings.setOutputDpi(dpi)
        settings.setDestinationCrs(self.height_layer.crs())
        render = QgsMapRendererParallelJob(settings)

        # if not hasattr(self, 'active_renders'):
        #     self.active_renders = []
        # self.active_renders.append(render)

        def finished():
            img = render.renderedImage()
            img.save(image_location, "png")
            self.export_finished(z_scale, min_elev, max_elev, elev_range, grid_res)

        render.finished.connect(finished)
        render.start()

    def export_finished(self, z_scale, min_elev, max_elev, elev_range, grid_res):
        # x-y-z scaling on import
        # need to add map scaling on albedo texture but I think thats
        # same as res
        copystr = f"X=100.0,Y=100.0,Z={z_scale:.6f}"
        QMessageBox.information(
            self.iface.mainWindow(),
            "3D Scaling Parameters",
            f"<b>Landscape XYZ Scaling:</b><br>"
            f"<code>{copystr}</code><br>"
            f"<b>Map Scaling:</b> <br> <code/>{grid_res:.2f}m </code><br>"
            f"<br><b>Elevation values<b/><br>"
            f"<b>Lowest:</b>  <code>{min_elev:.2f}m</code> <br>"
            f"<b>Highest:</b> <code>{max_elev:.2f}m</code> <br>"
            f"<b>Range:</b>   <code>{elev_range:.2f}m</code> <br>",
        )
